# Generated by Django 5.1.2 on 2024-10-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_complaint_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('На проверке', 'Submitted'), ('В процессе', 'In Progress'), ('Решено', 'Resolved')], default='submitted', max_length=20),
        ),
    ]
