# Generated by Django 5.1.2 on 2024-10-24 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_complaint_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('На проверке', 'Submitted'), ('В процессе', 'In Progress'), ('Решено', 'Resolved')], default='На проверке', max_length=20),
        ),
    ]
